name: build and deploy springHelloApp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  install:
    name: install required dependencies
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
  test-ubuntu:
    name: test on ubuntu
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: unit tests
        run: mvn -B test --file pom.xml
  test-windows:
    name: test on windows
    runs-on: windows-latest
    needs: install
    steps:
      - name: unit tests
        run: mvn -B test --file pom.xml
  test-macos:
    name: test on macos
    runs-on: macos-latest
    needs: install
    steps:
      - name: unit tests
        run: mvn -B test --file pom.xml
  build:
    name: build required dependencies
    runs-on: ubuntu-latest
    needs: [ install, test-ubuntu, test-windows, test-macos]
    steps:
      - name: build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/springhello:latest

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push the docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/springhello:latest
